import colors from './_colorsExportToJS.module.scss';

export const {
  colorBlack,
  colorCyan,
  colorCyanDark,
  colorCyanDarker,
  colorCyanLight,
  colorCyanLighter,
  colorCyanLightest,
  colorGray,
  colorGrayDark,
  colorGrayDarker,
  colorGrayDarkest,
  colorGrayLight,
  colorGrayLighter,
  colorGrayLightest,
  colorGreen,
  colorGreenDark,
  colorGreenLight,
  colorNavy,
  colorNavyDark,
  colorNavyLight,
  colorOrange,
  colorOrangeDark,
  colorOrangeLight,
  colorPastelBlue,
  colorPastelGreen,
  colorPastelRed,
  colorPastelYellow,
  colorRed,
  colorRedDark,
  colorRedLight,
  colorRedLighter,
  colorRedLightest,
  colorWhite,
  colorYellow,
  colorYellowDark,
} = colors;
